apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app
    spec:
      containers:
      - name: next-containers
        image: public.ecr.aws/x6i1u1x3/next:latest
        ports:
        - containerPort: 80